### ISSUE TITLE
Error during Make Ruby symlinks

### ISSUE THREAD

**Issue by rcwsr** [jlund/ansible-ruby-1.9.3#1]
Hi,
I get this error during provisioning:

```
failed: [site.dev] => (item=bundle) => {"failed": true, "gid": 0, "group": "root", "item": "bundle", "mode": "0755", "owner": "root", "path": "/usr/local/bin/bundle", "size": 462, "state": "file", "uid": 0}
msg: refusing to convert between file and link for /usr/local/bin/bundle
```

I've installed your ruby-common role, and added ruby-1.9.3 role as follows:

``` yaml
  roles:
    - { role: joshualund.ruby-1_9_3, sudo: yes }
```

I'm using ansible 1.8.2 and provisioning Ubuntu 14.04

**Comment by jlund** [comment]
I think that would happen if you already had something installed at `/usr/local/bin/bundler` that prevents the symlink from being made.

**Comment by rcwsr** [comment]
Yep, you're correct, Bundler had already previously been installed somehow. All sorted now, thanks.
